from pathlib import Path

path = Path("desktop_compact.py")
text = path.read_text(encoding="utf-8")


def replace_once(old: str, new: str) -> None:
    global text
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"expected one match, found {count}: {old[:120]!r}")
    text = text.replace(old, new, 1)


replace_once(
    "    def _clock_render_width(self) -> int:\n"
    "        # 150 px is a conservative reserve for the default clock/status group.\n"
    "        width = 150\n"
    "        clock = getattr(self, \"clock\", None)\n"
    "        if clock is not None:\n"
    "            try:\n"
    "                req = int(clock.winfo_reqwidth())\n"
    "                if req > 1:\n"
    "                    width = req\n"
    "            except tk.TclError:\n"
    "                pass\n"
    "        return width\n\n"
    "    def _cluster_horizontal_layout(self) -> tuple[int, int]:\n"
    "        # Treat the clock/status + visible Kyunghee silhouette as one cluster.\n"
    "        # Keep a fixed *visible* edge-to-edge gap at every scale; transparent PNG\n"
    "        # padding is deliberately excluded from the gap calculation.\n"
    "        timer_width, _timer_height = self._timer_size()\n"
    "        character_width, _character_height = self._character_render_size()\n"
    "        visible_left, _visible_top, visible_right, _visible_bottom = self._character_visible_bounds()\n"
    "        clock_width = self._clock_render_width()\n"
    "        visible_gap = 6\n"
    "        visible_character_width = max(1, visible_right - visible_left)\n"
    "        visible_cluster_width = clock_width + visible_gap + visible_character_width\n"
    "        cluster_left = max(18, round((timer_width - visible_cluster_width) / 2))\n"
    "        visible_character_left = cluster_left + clock_width + visible_gap\n"
    "        image_left = visible_character_left - visible_left\n"
    "        character_center = image_left + character_width / 2\n"
    "        return cluster_left, round(character_center - timer_width / 2)\n",
    "    def _clock_render_width(self) -> int:\n"
    "        # 150 px is a conservative reserve for the default clock/status group.\n"
    "        width = 150\n"
    "        clock = getattr(self, \"clock\", None)\n"
    "        if clock is not None:\n"
    "            try:\n"
    "                req = int(clock.winfo_reqwidth())\n"
    "                if req > 1:\n"
    "                    width = req\n"
    "            except tk.TclError:\n"
    "                pass\n"
    "        return width\n\n"
    "    def _clock_layout_width(self) -> int:\n"
    "        if not (self._effective_display_flag(\"show_time\") or self._effective_display_flag(\"show_status\")):\n"
    "            return 0\n"
    "        return self._clock_render_width()\n\n"
    "    def _message_render_width(self) -> int:\n"
    "        if not self._effective_display_flag(\"show_message\"):\n"
    "            return 0\n"
    "        speech = getattr(self, \"speech\", None)\n"
    "        if speech is not None:\n"
    "            try:\n"
    "                req = int(speech.winfo_reqwidth())\n"
    "                if req > 1:\n"
    "                    return req\n"
    "            except tk.TclError:\n"
    "                pass\n"
    "        wrap = min(360, max(250, self._scale(self.BUBBLE_WRAP)))\n"
    "        return wrap + 8\n\n"
    "    def _horizontal_union_bounds(self) -> tuple[float, float, int, int]:\n"
    "        visible_left, _visible_top, visible_right, _visible_bottom = self._character_visible_bounds()\n"
    "        visible_character_width = max(1, visible_right - visible_left)\n"
    "        clock_width = self._clock_layout_width()\n"
    "        visible_gap = 6 if clock_width else 0\n"
    "        character_visible_left = clock_width + visible_gap\n"
    "        character_visible_right = character_visible_left + visible_character_width\n"
    "        character_visible_center = character_visible_left + visible_character_width / 2\n"
    "        union_left = 0.0\n"
    "        union_right = float(character_visible_right)\n"
    "        message_width = self._message_render_width()\n"
    "        if message_width:\n"
    "            union_left = min(union_left, character_visible_center - message_width / 2)\n"
    "            union_right = max(union_right, character_visible_center + message_width / 2)\n"
    "        return union_left, union_right, clock_width, visible_gap\n\n"
    "    def _cluster_horizontal_layout(self) -> tuple[int, int]:\n"
    "        # Right-pack the complete visible union (clock/status, Kyunghee silhouette,\n"
    "        # and message) instead of centering it inside a generously oversized canvas.\n"
    "        timer_width, _timer_height = self._timer_size()\n"
    "        character_width, _character_height = self._character_render_size()\n"
    "        visible_left, _visible_top, _visible_right, _visible_bottom = self._character_visible_bounds()\n"
    "        union_left, union_right, clock_width, visible_gap = self._horizontal_union_bounds()\n"
    "        right_margin = 8\n"
    "        cluster_left = round(timer_width - right_margin - union_right)\n"
    "        # _timer_size guarantees at least 24 px on the union's left side.\n"
    "        cluster_left = max(cluster_left, round(24 - union_left))\n"
    "        visible_character_left = cluster_left + clock_width + visible_gap\n"
    "        image_left = visible_character_left - visible_left\n"
    "        character_center = image_left + character_width / 2\n"
    "        return cluster_left, round(character_center - timer_width / 2)\n",
)

replace_once(
    "    def _timer_size(self):\n"
    "        # Keep a generous click-through transparent canvas, but guarantee enough\n"
    "        # width for the whole visible cluster at every scale. The visible UI\n"
    "        # spacing itself stays fixed while only the artwork and canvas grow.\n"
    "        growth = self._layout_growth()\n"
    "        width = self.MIN_TIMER_SIZE[0] + round(growth * 3.60)\n"
    "        height = self.MIN_TIMER_SIZE[1] + round(growth * 3.40)\n"
    "        fixed_side_margins = 48\n"
    "        clock_reserve = 150\n"
    "        cluster_gap = 30\n"
    "        required_width = fixed_side_margins + clock_reserve + cluster_gap + self._scale(self.CHARACTER_MAX[0])\n"
    "        required_height = self._scale(self.CHARACTER_MAX[1]) + 130\n"
    "        return max(width, required_width), max(height, required_height)\n",
    "    def _timer_size(self):\n"
    "        # Size from the actual visible horizontal union. Transparent PNG padding\n"
    "        # is excluded, so large widget scales no longer reserve invisible width.\n"
    "        growth = self._layout_growth()\n"
    "        height = self.MIN_TIMER_SIZE[1] + round(growth * 3.40)\n"
    "        union_left, union_right, _clock_width, _visible_gap = self._horizontal_union_bounds()\n"
    "        union_width = max(1.0, union_right - union_left)\n"
    "        left_margin = 24\n"
    "        right_margin = 8\n"
    "        required_width = round(union_width + left_margin + right_margin)\n"
    "        width = max(360, required_width)\n"
    "        required_height = self._scale(self.CHARACTER_MAX[1]) + 130\n"
    "        return width, max(height, required_height)\n",
)

path.write_text(text, encoding="utf-8")
